name: tdlib_generator

environment:
  sdk: ">=2.19.0 <3.0.0"


dependencies:
  json_annotation: 4.8.1
  code_builder: 4.5.0
  dart_style: 2.3.2

dev_dependencies:
  build_runner: 2.4.6
  json_serializable: 6.7.1